// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace Planty.Models
{
    public partial class CallToAction
    {
        public const string Codename = "call_to_action";
        public const string LinkUrlCodename = "link_url";
        public const string SettingsCodename = "settings";
        public const string TitleCodename = "title";

        public string LinkUrl { get; set; }
        public IEnumerable<IMultipleChoiceOption> Settings { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}