// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace Planty.Models
{
    public partial class FrequentlyAskedQuestion
    {
        public const string Codename = "frequently_asked_question";
        public const string AnswerCodename = "answer";
        public const string QuestionCodename = "question";

        public IRichTextContent Answer { get; set; }
        public string Question { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}