// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Planty.Models
{
    public partial class HeaderSection
    {
        public const string Codename = "header_section";
        public const string BackgroundImageCodename = "background_image";
        public const string HeadlineCodename = "headline";
        public const string SubtitleCodename = "subtitle";

        public IEnumerable<IAsset> BackgroundImage { get; set; }
        public string Headline { get; set; }
        public IRichTextContent Subtitle { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}