// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace Planty.Models
{
    public partial class HeroSection
    {
        public const string Codename = "hero_section";
        public const string BackgroundImageCodename = "background_image";
        public const string ButtonsCodename = "buttons";
        public const string ContentCodename = "content";

        public IEnumerable<IAsset> BackgroundImage { get; set; }
        public IRichTextContent Buttons { get; set; }
        public IRichTextContent Content { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}