// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Planty.Models
{
    public partial class Product
    {
        public const string Codename = "product";
        public const string CategoryCodename = "category";
        public const string DescriptionCodename = "description";
        public const string ImageCodename = "image";
        public const string PriceCodename = "price";
        public const string ProductIdCodename = "product_id";
        public const string SettingsCodename = "settings";
        public const string SlugCodename = "slug";
        public const string TitleCodename = "title";

        public IEnumerable<ITaxonomyTerm> Category { get; set; }
        public IRichTextContent Description { get; set; }
        public IEnumerable<IAsset> Image { get; set; }
        public decimal? Price { get; set; }
        public string ProductId { get; set; }
        public IEnumerable<IMultipleChoiceOption> Settings { get; set; }
        public string Slug { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}