// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Planty.Models
{
    public partial class ProductProperty
    {
        public const string Codename = "product_property";
        public const string NameCodename = "name";
        public const string OptionsCodename = "options";
        public const string PlaceholderCodename = "placeholder";
        public const string SettingsCodename = "settings";
        public const string TypeCodename = "type";
        public const string ValueCodename = "value";

        public string Name { get; set; }
        public string Options { get; set; }
        public string Placeholder { get; set; }
        public IEnumerable<IMultipleChoiceOption> Settings { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<IMultipleChoiceOption> Type { get; set; }
        public string Value { get; set; }
    }
}