// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Planty.Models
{
    public partial class PromotionSection
    {
        public const string Codename = "promotion_section";
        public const string CallToAction40ed566LinkUrlCodename = "call_to_action_40ed566__link_url";
        public const string CallToAction40ed566LinkedPageCodename = "call_to_action_40ed566__linked_page";
        public const string CallToAction40ed566SettingsCodename = "call_to_action_40ed566__settings";
        public const string CallToAction40ed566TextCodename = "call_to_action_40ed566__text";
        public const string ImageCodename = "image";
        public const string SubtitleCodename = "subtitle";
        public const string TitleCodename = "title";

        public IEnumerable<object> CallToAction40ed566LinkedPage { get; set; }
        public string CallToAction40ed566LinkUrl { get; set; }
        public IEnumerable<IMultipleChoiceOption> CallToAction40ed566Settings { get; set; }
        public string CallToAction40ed566Text { get; set; }
        public IEnumerable<IAsset> Image { get; set; }
        public string Subtitle { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}