// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace Planty.Models
{
    public partial class Testimonial
    {
        public const string Codename = "testimonial";
        public const string ContentCodename = "content";
        public const string LocationCodename = "location";
        public const string NameCodename = "name";

        public IRichTextContent Content { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}